### ISSUE TITLE
New lottie animations for v3.0

### ISSUE THREAD

**Issue by basmilius** [basmilius/weather-icons#12]
Review all animations for all icons and update them where needed.

- [x] alert-avalanche-danger
- [x] alert-falling-rocks
- [x] barometer
- [x] beanie
- [x] celsius
- [x] clear-day
- [x] clear-night
- [x] cloud-down
- [x] cloud-up
- [x] cloudy
- [x] code-green
- [x] code-orange
- [x] code-red
- [x] code-yellow
- [x] compass
- [x] drizzle
- [x] dust
- [x] dust-day
- [x] dust-night
- [x] dust-wind
- [x] extreme
- [x] extreme-day
- [x] extreme-day-drizzle
- [x] extreme-day-fog
- [x] extreme-day-hail
- [x] extreme-day-haze
- [x] extreme-day-rain
- [x] extreme-day-sleet
- [x] extreme-day-smoke
- [x] extreme-day-snow
- [x] extreme-drizzle
- [x] extreme-fog
- [x] extreme-hail
- [x] extreme-haze
- [x] extreme-night
- [x] extreme-night-drizzle
- [x] extreme-night-fog
- [x] extreme-night-hail
- [x] extreme-night-haze
- [x] extreme-night-rain
- [x] extreme-night-sleet
- [x] extreme-night-smoke
- [x] extreme-night-snow
- [x] extreme-rain
- [x] extreme-sleet
- [x] extreme-smoke
- [x] extreme-snow
- [x] fahrenheit
- [x] falling-stars
- [x] flag-gale-warning
- [x] flag-hurricane-warning
- [x] flag-small-craft advisory
- [x] flag-storm-warning
- [x] fog
- [x] fog-day
- [x] fog-night
- [x] glove
- [x] hail
- [x] haze
- [x] haze-day
- [x] haze-night
- [x] horizon
- [x] humidity
- [x] hurricane
- [x] lightning-bolt
- [x] mist
- [x] moon-first-quarter
- [x] moon-full
- [x] moon-last-quarter
- [x] moon-new
- [x] moon-waning-crescent
- [x] moon-waning-gibbous
- [x] moon-waxing-crescent
- [x] moon-waxing-gibbous
- [x] moonrise
- [x] moonset
- [x] not-available
- [x] overcast
- [x] overcast-day
- [x] overcast-day-drizzle
- [x] overcast-day-fog
- [x] overcast-day-hail
- [x] overcast-day-haze
- [x] overcast-day-rain
- [x] overcast-day-sleet
- [x] overcast-day-smoke
- [x] overcast-day-snow
- [x] overcast-drizzle
- [x] overcast-fog
- [x] overcast-hail
- [x] overcast-haze
- [x] overcast-night
- [x] overcast-night-drizzle
- [x] overcast-night-fog
- [x] overcast-night-hail
- [x] overcast-night-haze
- [x] overcast-night-rain
- [x] overcast-night-sleet
- [x] overcast-night-smoke
- [x] overcast-night-snow
- [x] overcast-rain
- [x] overcast-sleet
- [x] overcast-smoke
- [x] overcast-snow
- [x] partly-cloudy-day
- [x] partly-cloudy-day-drizzle
- [x] partly-cloudy-day-fog
- [x] partly-cloudy-day-hail
- [x] partly-cloudy-day-haze
- [x] partly-cloudy-day-rain
- [x] partly-cloudy-day-sleet
- [x] partly-cloudy-day-smoke
- [x] partly-cloudy-day-snow
- [x] partly-cloudy-night
- [x] partly-cloudy-night-drizzle
- [x] partly-cloudy-night-fog
- [x] partly-cloudy-night-hail
- [x] partly-cloudy-night-haze
- [x] partly-cloudy-night-rain
- [x] partly-cloudy-night-sleet
- [x] partly-cloudy-night-smoke
- [x] partly-cloudy-night-snow
- [x] pollen
- [x] pollen-flower
- [x] pollen-grass
- [x] pollen-tree
- [x] pressure-high
- [x] pressure-high-alt
- [x] pressure-low
- [x] pressure-low-alt
- [x] rain
- [x] rainbow
- [x] rainbow-clear
- [x] raindrop
- [x] raindrop-measure
- [x] raindrops
- [x] sleet
- [x] smoke
- [x] smoke-particles
- [x] snow
- [x] snowflake
- [x] snowman
- [x] solar-eclipse
- [x] star
- [x] starry-night
- [x] sun-hot
- [x] sunrise
- [x] sunset
- [x] thermometer
- [x] thermometer-celsius
- [x] thermometer-colder
- [x] thermometer-fahrenheit
- [x] thermometer-glass
- [x] thermometer-glass-celsius
- [x] thermometer-glass-fahrenheit
- [x] thermometer-mercury
- [x] thermometer-mercury-cold
- [x] thermometer-moon
- [x] thermometer-raindrop
- [x] thermometer-snow
- [x] thermometer-sun
- [x] thermometer-warmer
- [x] thermometer-water
- [x] thunderstorms
- [x] thunderstorms-day
- [x] thunderstorms-day-extreme
- [x] thunderstorms-day-extreme-rain
- [x] thunderstorms-day-extreme-snow
- [x] thunderstorms-day-overcast
- [x] thunderstorms-day-overcast-rain
- [x] thunderstorms-day-overcast-snow
- [x] thunderstorms-day-rain
- [x] thunderstorms-day-snow
- [x] thunderstorms-extreme
- [x] thunderstorms-extreme-rain
- [x] thunderstorms-extreme-snow
- [x] thunderstorms-night
- [x] thunderstorms-night-extreme
- [x] thunderstorms-night-extreme-rain
- [x] thunderstorms-night-extreme-snow
- [x] thunderstorms-night-overcast
- [x] thunderstorms-night-overcast-rain
- [x] thunderstorms-night-overcast-snow
- [x] thunderstorms-night-rain
- [x] thunderstorms-night-snow
- [x] thunderstorms-overcast
- [x] thunderstorms-overcast-rain
- [x] thunderstorms-overcast-snow
- [x] thunderstorms-rain
- [x] thunderstorms-snow
- [x] tide-high
- [x] tide-low
- [x] time-afternoon
- [x] time-evening
- [x] time-late-afternoon
- [x] time-late-evening
- [x] time-late-morning
- [x] time-late-night
- [x] time-morning
- [x] time-night
- [x] tornado
- [x] umbrella
- [x] umbrella-wind
- [x] umbrella-wind-alt
- [x] uv-index
- [x] uv-index-1
- [x] uv-index-2
- [x] uv-index-3
- [x] uv-index-4
- [x] uv-index-5
- [x] uv-index-6
- [x] uv-index-7
- [x] uv-index-8
- [x] uv-index-9
- [x] uv-index-10
- [x] uv-index-11
- [x] wind
- [x] wind-alert
- [x] wind-beaufort-0
- [x] wind-beaufort-1
- [x] wind-beaufort-2
- [x] wind-beaufort-3
- [x] wind-beaufort-4
- [x] wind-beaufort-5
- [x] wind-beaufort-6
- [x] wind-beaufort-7
- [x] wind-beaufort-8
- [x] wind-beaufort-9
- [x] wind-beaufort-10
- [x] wind-beaufort-11
- [x] wind-beaufort-12
- [x] wind-offshore
- [x] wind-onshore
- [x] wind-snow
- [x] windsock
- [x] windsock-weak
